Add sythesis script and finish matlab data generation

diff --git a/build/Makefile b/build/Makefile
--- a/build/Makefile
+++ b/build/Makefile
@@ -1,10 +1,11 @@
 GEN = python ./scripts/generate_random_data.py
+GEN_MATLAB = python ./scripts/generate_matlab_data.py
 
 prepare:
 	mkdir -p output
 
 randomNumber1x5_Seed:
-	$(GEN) ./data/seed 8 5
+	$(GEN) ./data/seed 5 5
 
 randomRBMData:
 	$(GEN)  ./data/image    1   15
@@ -12,6 +13,17 @@ randomRBMData:
 	$(GEN)  ./data/Hbias    12  5
 	$(GEN)  ./data/Cweight  12  5*2
 	$(GEN)  ./data/Cbias    12  2
+
+
+generate_matlab_data:
+	rm -rf ./data/mnist/verilog/* $@
+	rm -rf ./data/model/verilog/* $@
+	echo "Generating Mnist Test Data to verilog format." $@
+	$(GEN_MATLAB)  ./data/mnist/matlab/data.mat mnist  ./data/mnist/verilog/ 4  && echo "Finished" || echo "Error Occured" $@
+	echo "Generating RBM Model Data to verilog format." $@
+	$(GEN_MATLAB)  ./data/model/matlab/data.mat  mnist_rbm_model  ./data/model/verilog/ 4 && echo "Finished" || echo "Error Occured" $@
+
+
 
 
 
@@ -49,5 +61,17 @@ ClassifyLayer_TB: prepare
 	iverilog -o ./output/design_ClassifyLayer_TB ../test_bench/ClassifyLayer_tb.v
 	vvp ./output/design_ClassifyLayer_TB
 
+
+Main_wave:
+	gtkwave ./dumpFolder/Main.vcd &
+
+
+Main_syth:
+	yosys  -Q -T -s ./scripts/generate_main_netlist.tcl
+
+
+Main_real_TB: prepare
+	iverilog -o ./output/design_Main_Real_TB ../test_bench/Main_Real_tb.v
+	vvp ./output/design_Main_Real_TB
 
 all_TB: sigmoid_TB MatrixAdd_TB MatrixMul_TB RandomGenerator_TB
